new#Java
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

#Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

#NeoForge
neo_version=21.1.228
loader_version_range=[4,)

#Create
create_version = 6.0.11-286
ponder_version = 1.0.82+mc1.21.1
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67

#Mod
mod_id=createrailgrinding
mod_name=Create Rail Grinding
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.juniknytt.createrailgrinding
mod_authors=Juni Knytt
mod_description=Adds Rail Grinding to Create Mod.\nRide on Train Tracks using Diving Shoes.
