org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

#Parchment
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

#Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]

#Forge
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

#Create (6.x backport for 1.20.1 Forge) / Ponder / Flywheel / Registrate
create_version=6.0.8-291
create_version_range=[6.0.8,)
ponder_version=1.0.91
flywheel_version=1.0.5
registrate_version=MC1.20-1.3.3
mixinextras_version=0.5.3

#Mod
mod_id=createrailgrinding
mod_name=Create: Rail Grinding
mod_license=MIT
mod_version=1.2.1
mod_group_id=net.juniknytt.createrailgrinding
mod_authors=Juni Knytt
mod_description=Adds Rail Grinding to Create Mod.\nRide on Train Tracks using Diving Shoes.
